# Test your FastAPI endpoints

GET http://127.0.0.1:8001/api/coordenadas-confirmadas
Accept: application/json


GET http://127.0.0.1:8001/api/exoplanetas-candidatos-ml
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
